### ISSUE TITLE
睡眠问题-短时间睡眠没问题，睡眠时间长一点就会唤醒时重启。

### ISSUE THREAD

**Issue by leizhiren** [aaronlui/Hackintosh-B460M-10400-5500XT#1]
类型 | 配置
CPU | intel i5-10400
主板 | 技嘉B460M AORUS PRO
内存 | 海盗船16 x 4 64GB
显卡 | 讯景 5500XT
无线网卡 | BCM94360CD

睡眠问题，短时间睡眠没问题，睡眠睡稍微久一点，唤醒一定会重启。

**Comment by aaronlui** [comment]
用Hackintool修复一下电源试试

**Comment by leizhiren** [comment]
独显拔掉后进不去系统，核显是屏蔽了吗？
