### ISSUE TITLE
独显拔掉后，核显能显示但无法进入系统。

### ISSUE THREAD

**Issue by leizhiren** [aaronlui/Hackintosh-B460M-10400-5500XT#2]
类型 | 配置
CPU | intel i5-10400
主板 | 技嘉B460M AORUS PRO
内存 | 海盗船16 x 4 64GB
显卡 | 讯景 5500XT
无线网卡 | BCM94360CD

是核显屏蔽掉了吗？

**Comment by aaronlui** [comment]
独显和核显配置是不一样的，用独显需要配置成核显只参与计算
两个地方需要修改，设备ID和启动参数
https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#deviceproperties
https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#nvram

**Comment by leizhiren** [comment]
感谢，根据你给的链接看了OC的引导文档，看起来似乎只需要改DeviceProperties中的AAPL,ig-platform-id为00009B3E，如下图所示：
![image](https://user-images.githubusercontent.com/24837873/183026722-d01b21bb-08b2-4895-8668-752a119f447f.png)
至于boot-args中，你在EFI中已经默认已经添加了agdpmod=pikera，而我们的硬件也不是NVIDIA。我不是很能明白在boot-args中修改什么，启动参数为你的EFI的默认参数，如下图：
![image](https://user-images.githubusercontent.com/24837873/183027278-03a71aab-7ef4-4682-b005-503a78747485.png)

**Comment by aaronlui** [comment]
agdpmod=pikera是为了解决5500XT黑屏问题的，指的是NAVI不是N卡，不过如果你使用正常的话就不用管了
